### ISSUE TITLE
Credenciales del servidor

### ISSUE THREAD

**Issue by DavidDavilaDev** [DavidDavilaDev/mario#3]
Credenciales anteriores no funcionales

@ingreyeslara

**Comment by ingreyeslara** [comment]
![1111](https://github.com/Guayaba15/mario/assets/75334788/37661284-cc22-4f24-920a-9f6793bdca45)
![2222](https://github.com/Guayaba15/mario/assets/75334788/9bddc9a8-1513-4cf9-ad44-92fc23c25d91)
Password:
Guayaba_2024
